import turtle


#turtle.shape("turtle")
turtle.color("purple") 
turtle.pensize(7)
turtle.forward(50)
turtle.left(180)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.right(180)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.forward(20)
turtle.left(90)
turtle.forward(50)
turtle.right(180)
turtle.pendown()
turtle.forward(100)
turtle.left(120)
turtle.forward(90)
turtle.left(90)
turtle.forward(75)
turtle.left(60)
turtle.forward(40)
turtle.left(90)
turtle.forward(10)
